name: lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install linting dependencies
        run: |
            python -m pip install --upgrade pip
            pip install flake8

      - name: Run linting tests
        run: flake8 dotgit --count --statistics --show-source
