name: Test
on: push
defaults:
    working-directory: 'tests'
jobs:
    strategy:
        matrix:
            os: [ubuntu-16.04, ubuntu-18.04, macos-latest]
    run_tests:
        runs-on: '${{ matrix.os }}'
        steps:
            - run: './test.py'
